{
 "title": "pg_auto_failover overview",
 "tags": [
  "postgres",
  "pg_auto_failover"
 ],
 "panels": [
  {
   "title": "Node health",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pg_auto_failover_node_state_health_code",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Replication replay lag",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_stat_replication_replay_lag_bytes",
     "legendFormat": "{{application_name}}"
    }
   ]
  },
  {
   "title": "Node state code",
   "type": "bargauge",
   "description": "Numerical state code reported by pg_auto_failover (primary=3, secondary=2, wait_standby=1, draining=0, single=4).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_auto_failover_node_state_reported_state_code",
     "legendFormat": "{{nodename}}"
    }
   ]
  }
 ]
}